### ISSUE TITLE
CURL Error issue

### ISSUE THREAD

**Issue by armandvanderwalt** [ICE3X/v2-PHP#1]
You seem to have an issue with your usage of CURL, you are trying to access the curl_error after closing curl.

Your code should rather be like this:

`private function get($url, array $data)
    {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; ICE3X PHP client; '.php_uname('s').'; PHP/'.phpversion().')');
        curl_setopt($ch, CURLOPT_URL, 'https://ice3x.com/api/v1/'.$url.'?'.http_build_query($data));
        $result = curl_exec($ch);
        
		$curlError = curl_error($ch);
		
		curl_close($ch);
		
        if ($result === false) {
            throw new Exception('Could not get reply: '. $curlError);
        }

        if (!($result = json_decode($result, true))) {
            switch (json_last_error()) {
            case JSON_ERROR_DEPTH:
                $error = 'Reached the maximum stack depth';
                break;
            case JSON_ERROR_STATE_MISMATCH:
                $error = 'Incorrect discharges or mismatch mode';
                break;
            case JSON_ERROR_CTRL_CHAR:
                $error = 'Incorrect control character';
                break;
            case JSON_ERROR_SYNTAX:
                $error = 'Syntax error or JSON invalid';
                break;
            case JSON_ERROR_UTF8:
                $error = 'Invalid UTF-8 characters, possibly invalid encoding';
                break;
            default:
                $error = 'Unknown error';
            }
            throw new Exception($error);
        }

        return $result;
    }

    private function post($url, array $data)
    {
        $post_data = http_build_query($data);

        $sign = hash_hmac('sha512', $post_data, $this->_privateKey);
        $headers = array("Key: $this->_publicKey", "Sign: $sign");

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; ICE3X PHP client; '.php_uname('s').'; PHP/'.phpversion().')');
        curl_setopt($ch, CURLOPT_URL, 'https://ice3x.com/api/v1/'.$url);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);

		$curlError = curl_error($ch);
		
		curl_close($ch);

        if ($result === false) {
            throw new Exception('Could not get reply: '. $curlError);
        }

        if (!($result = json_decode($result, true))) {
            switch (json_last_error()) {
            case JSON_ERROR_DEPTH:
                $error = 'Reached the maximum stack depth';
                break;
            case JSON_ERROR_STATE_MISMATCH:
                $error = 'Incorrect discharges or mismatch mode';
                break;
            case JSON_ERROR_CTRL_CHAR:
                $error = 'Incorrect control character';
                break;
            case JSON_ERROR_SYNTAX:
                $error = 'Syntax error or JSON invalid';
                break;
            case JSON_ERROR_UTF8:
                $error = 'Invalid UTF-8 characters, possibly invalid encoding';
                break;
            default:
                $error = 'Unknown error';
            }
            throw new Exception($error);
        }

        return $result;
    }`

You are also missing a use statement at the top for Exception

`use Exception;`

**Comment by armandvanderwalt** [comment]
I have also created an updated api wrapper for .NET https://github.com/armandvanderwalt/ice3x-api

**Comment by Crypto100101** [comment]
@armandvanderwalt Good catch, I will make this change. Thanks !
